
spring :
  application :
    name : cloud-config-server-service

  cloud :
    config :
      server :
        git :
          uri : https://github.com/mdhiman/environment-variable-repo
          
server :
  port : ${port:8888}